name: mitra_abadi
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  data_table_2: ^2.5.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  http: ^1.2.1
  icons_plus: ^5.0.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  intl_translation: ^0.20.0
  json_annotation: ^4.9.0
  meta: ^1.11.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
